# GitHub Sponsors/Funding metadata: shows "Sponsor this project" button.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom: ["https://www.buymeacoffee.com/9m2pju", "https://wise.com/pay/me/faizulz13"]
