[supervisord]
nodaemon=true
user=root
logfile=/data/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:opentakserver]
command=opentakserver
stdout_logfile=/data/logs/api.log
stderr_logfile=/data/logs/api.err
autorestart=true
startretries=5
stopwaitsecs=30
stopsignal=INT
priority=1

[program:eud_handler_ssl]
command=/opt/ots/wait-for-ca.sh
stdout_logfile=/data/logs/eud_handler_ssl.log
stderr_logfile=/data/logs/eud_handler_ssl.err
autorestart=true
startretries=10
startsecs=5
priority=10

[program:cot_parser]
command=cot_parser
stdout_logfile=/data/logs/cot_parser.log
stderr_logfile=/data/logs/cot_parser.err
autorestart=true
startretries=10
priority=10
