[supervisord]
nodaemon=true
user=root
logfile=/data/ots/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/data/ots/logs/nginx.log
stderr_logfile=/data/ots/logs/nginx.err
autorestart=true
startretries=5
priority=5

[program:opentakserver]
command=opentakserver
stdout_logfile=/data/ots/logs/api.log
stderr_logfile=/data/ots/logs/api.err
autorestart=true
startretries=5
stopwaitsecs=30
stopsignal=INT
priority=1

[program:eud_handler_ssl]
command=/opt/ots/wait-for-ca.sh
stdout_logfile=/data/ots/logs/eud_handler_ssl.log
stderr_logfile=/data/ots/logs/eud_handler_ssl.err
autorestart=true
startretries=10
startsecs=5
priority=10

[program:cot_parser]
command=cot_parser
stdout_logfile=/data/ots/logs/cot_parser.log
stderr_logfile=/data/ots/logs/cot_parser.err
autorestart=true
startretries=10
priority=10
