#!/bin/bash
# Waits for the CA to be generated by the API, then starts the EUD handler
set -e

CA_DIR="${OTS_DATA_FOLDER:-/data/ots}/ca"
echo "[wait-for-ca] Waiting for CA certs at ${CA_DIR}..."
for i in $(seq 1 60); do
  if [ -f "${CA_DIR}/ca.pem" ]; then
    echo "[wait-for-ca] CA certs found."
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo "[wait-for-ca] WARNING: CA certs not found after 60s, starting anyway..."
  fi
  sleep 2
done

exec eud_handler --ssl
