#!/bin/bash
# Author: 9M2PJU - https://hamradio.my

# Waits for the CA to be generated by the API, then starts the EUD handler
set -euo pipefail

CA_DIR="${OTS_DATA_FOLDER:-/data/ots}/ca"
echo "[wait-for-ca] Waiting for CA certs at ${CA_DIR}..."
for i in $(seq 1 60); do
  if [ -f "${CA_DIR}/ca.pem" ]; then
    echo "[wait-for-ca] CA certs found."
    exec eud_handler --ssl
  fi
  sleep 2
done
echo "[wait-for-ca] WARNING: CA certs not found after 120s, starting anyway..."
exec eud_handler --ssl
